
source 'https://github.com/XiangtaiCompany/XTPrivatePods.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'PodTest' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'XTLocationUtils'
  pod 'XTHttpRequestUtils'
  pod "WaterFall"
  pod "CocoaLumberjack"
  pod "skpsmtpmessage"
end
